card_central/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "listings#index"
  resources :listings
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

card_central/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

card_central/app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  has_one_attached :photo
end

card_central/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
end

card_central/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

card_central/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
    if user_signed_in?
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
          name: @listing.title,
          description: @listing.description,
          amount: @listing.price,
          currency: 'aud',
          quantity: 1
        }],
        payment_intent_data: {
          metadata: {
            user_id: current_user.id,
            listing_id: @listing.id
          }
        },
        success_url: "#{root_url}payments/success?listingId=#{@listing.id}",
        # todo - check if we can use listings_path
        cancel_url: "#{root_url}listings"
      )

      @session_id = session.id
    end
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    @listing.photo.attach(params[:listing][:photo])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :description, :price, :sold)
    end
end

card_central/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhook]

  def success
  end

  def webhook
    payment_id = params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_id)
    listing_id = payment.metadata.listing_id
    user_id = payment.metadata.user_id

    listing = Listing.find(listing_id.to_i)
    listing.sold = true
    listing.save

    status 200
  end
end

card_central/app/helpers/application_helper.rb
module ApplicationHelper
end

card_central/app/helpers/listings_helper.rb
module ListingsHelper
end

card_central/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CardCentral</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

card_central/app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :sold %>
    <%= form.check_box :sold %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

card_central/app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

card_central/app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>
<p>If you can see this in production, then your deployment was successful</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.description %></td>
        <td><%= listing.price %></td>
        <td><%= listing.sold %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

card_central/app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

card_central/app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @listing.sold %>
</p>

<% if @listing.photo.attached? %>
  <p>
    <strong>Photo:</strong>
    <%= image_tag @listing.photo %>
  </p>
<% end %>

<% if @listing.sold %>
  <p>Listing already sold!</p>
<% else %>
  <% if user_signed_in? %>
    <button data-stripe="payment">
    Buy Now!
    </button>
  <% else %>
    <%= button_to "Buy Now!", new_user_registration_path, method: :get %>
  <% end %>
<% end %>



<script src="https://js.stripe.com/v3/"></script>
<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      )

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      })
    })
</script>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

card_central/app/views/payments/success.html.erb
<p>Wooo! Payment successful</p>
<%= link_to "Listings", root_path %>

card_central/app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
      <%= link_to "Card Central", listings_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            <%= link_to "Listings", listings_path, class: "nav-link active" %>
          </li>

          <li class="nav-item">
            <%= link_to "Create Listing", new_listing_path, class: "nav-link active" %>
          </li>

          <li class="nav-item">
            <% if user_signed_in? %>
              <%# logout button (only show when logged in) %>
              <%= link_to "Log out", destroy_user_session_path, method: "delete", class: "nav-link active" %>
            <% else %>
              <%# log in button - only show this when logged out %>
              <%= link_to "Log in", new_user_session_path, class: "nav-link active" %>
            <% end %>
          </li>
        </ul>
        <%# bring this back in when search has been implemented %>
        <%# <form>
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form> %>
      </div>
    </div>
  </nav>
</header>